version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=production

  frontend:
    build: ./frontend/my-react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
